### ISSUE TITLE
Communication error with Tableau 10.2 and Neo4j 3.1

### ISSUE THREAD

**Issue by graphadvantage** [ralfbecher/tableau-neo4j-wdc#7]
Hi Ralf,

This is a great update! Glad to see Bolt in use.

I have not be able to get it to work successfully with Neo4j 3.1.1 and Tableau 10.2 (trial).

I get a "error communicating with the data source message"

I've tried bolt://localhost and bolt+router://localhost  as well as declaring the port 7687

can you please confirm?

<img width="904" alt="tableau_error" src="https://cloud.githubusercontent.com/assets/5991751/23707179/401fd81a-03c6-11e7-8c88-920002fba3c7.png">

**Comment by graphadvantage** [comment]
Hi Ralf,

One more comment - can you please update the readme with details on how to register and use the .jar file as Neo4j server plugin

**Comment by ralfbecher** [comment]
Hi Michael,

unfortunately, the WDC as extension.jar doesn't work since Neo4j doesn't run w/o authentication anymore and Tableau doesn't provide a function to authenticate to the WDC website (the connector's web form).

**Comment by graphadvantage** [comment]
Hi Ralf,

I believe we have resolved this, I suspect it is a Tableau issue. 

The fix was a shutdown restart after installing Tableau. 

After that everything worked fine.

The only detail I saw was an error message that 'error 23 semaphore' with 10.1.3

10.2 had no error messages other than the one I shared.

I'll update the issue.

Thanks, 

Michael

**Comment by graphadvantage** [comment]
Some more testing - I see some flakey-ness in connection after a sleep, I think it's an environmental issue related to how our work laptop are set up.   Restarting seems to fix it.  Closing this issue, thanks.
